apiVersion: apps/v1
kind: Deployment
metadata:
  name: intellmeet-backend
  labels:
    app.kubernetes.io/name: intellmeet-backend
    app.kubernetes.io/part-of: intellmeet
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: intellmeet-backend
  template:
    metadata:
      labels:
        app: intellmeet-backend
        app.kubernetes.io/name: intellmeet-backend
        app.kubernetes.io/part-of: intellmeet
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: backend
          image: intellmeet-backend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
          envFrom:
            - configMapRef:
                name: intellmeet-config
            - secretRef:
                name: intellmeet-secrets
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
