apiVersion: v1
kind: Service
metadata:
  name: intellmeet-backend-service
  labels:
    app.kubernetes.io/name: intellmeet-backend
    app.kubernetes.io/part-of: intellmeet
    app.kubernetes.io/component: backend
spec:
  type: NodePort
  selector:
    app: intellmeet-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30050
