apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: intellmeet
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
